In [1]:
import numpy as np
image=np.array([[100,150,200],[50,180,240]])
bright_image=np.clip(image+50,0,255)
print(bright_image)

[[150 200 250]
 [100 230 255]]


In [2]:
temp=np.array([25,30,-15,40,60,18,-5])
clean_data=temp[(temp >= -10) & (temp <= 50)]
print(clean_data)

[25 30 40 18 -5]


In [3]:
data=np.array([10,20,30,40,50])
normalized=(data - data.min())/(data.max()-data.min())
print(normalized)

[0.   0.25 0.5  0.75 1.  ]


In [4]:
sales=np.array([[10,20,30,40,50],[15,25,35,45,55],[12,22,32,42,52]])
print(sales.sum(axis=1))
print(sales.mean(axis=0))

[150 175 160]
[12.33333333 22.33333333 32.33333333 42.33333333 52.33333333]


In [5]:
n1= np.array([[1,2],[3,4]])
n2=np.array([[5,6],[7,8]])
matrix_mul=np.matmul(n1,n2)
print(matrix_mul)

[[19 22]
 [43 50]]


In [6]:
import pandas as pd
df=pd.DataFrame({"order_id":[101,102,103,104,105],
                 "customer":["A","B","C","D","E"],
                 "amount":[500,800,300,900,400],
                 "status":["completed","pending","completed","pending","completed"]})
completed=df[df["status"]=="completed"]
print(completed)
print("Total_revenue:",completed["amount"].sum())
print(completed.nlargest(3,"amount"))

   order_id customer  amount     status
0       101        A     500  completed
2       103        C     300  completed
4       105        E     400  completed
Total_revenue: 1200
   order_id customer  amount     status
0       101        A     500  completed
4       105        E     400  completed
2       103        C     300  completed


In [9]:
df=pd.DataFrame({"employee":["A","B","C","D"],
                 "department":["HR","IT","HR","IT"],
                 "salary":[30000,50000,20000,70000]})
avg_salary=df.groupby("department")["salary"].mean()
print(avg_salary)
print("Department with highest average salary:")
print(avg_salary.idxmax())

department
HR    25000.0
IT    60000.0
Name: salary, dtype: float64
Department with highest average salary:
IT


In [6]:
import numpy as np
import pandas as pd
df=pd.DataFrame({"marks":[80,np.nan,70,np.nan,90]})
print(df.isnull())
df["marks"].fillna(df["marks"].mean(),inplace=True)
print(df)


   marks
0  False
1   True
2  False
3   True
4  False
   marks
0   80.0
1   80.0
2   70.0
3   80.0
4   90.0


C:\Users\MEGHANA\AppData\Local\Temp\ipykernel_10060\2360469706.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["marks"].fillna(df["marks"].mean(),inplace=True)


In [ ]:
import pandas as pd
df = pd.DataFrame({
    "timestamp":["2024-01-10","2024-05-20","2025-03-15"],
    "log_message":["ERROR: File missing",
                   "Success",
                   "ERROR: Connection failed"]})
df["timestamp"] = pd.to_datetime(df["timestamp"])
df["year"] = df["timestamp"].dt.year
errors = df[df["log_message"].str.contains("ERROR")]
print(errors)
print(errors.groupby("year").size())

   timestamp               log_message  year
0 2024-01-10       ERROR: File missing  2024
2 2025-03-15  ERROR: Connection failed  2025
year
2024    1
2025    1
dtype: int64


In [ ]:
import pandas as pd
customers = pd.DataFrame({
    "customer_id":[1,2,3],
    "customer_name":["A","B","C"]
})
orders = pd.DataFrame({
    "customer_id":[1,2,1,3],
    "amount":[500,700,300,400]
})
merged = pd.merge(customers, orders, on="customer_id")
print(merged)
total_purchase = merged.groupby("customer_name")["amount"].sum()
print(total_purchase)

   customer_id customer_name  amount
0            1             A     500
1            1             A     300
2            2             B     700
3            3             C     400
customer_name
A    800
B    700
C    400
Name: amount, dtype: int64
